### ISSUE TITLE
Remove `canary` releases

### ISSUE THREAD

**Issue by endocrimes** [spinframework/spin-plugin-kube#48]
We don't do mutable tags in SpinKube projects where avoidable due to their frequent issues and overhead when trying to understand the bits you are installing.

Is there a reason to have `canary` releases rather than artifacts on commits that can be fetched by those who want to use them?

If not please can we drop those before we cut our first releases?

**Comment by bacongobbler** [comment]
Coming back to this conversation. I think it'd be okay to ask developers to compile from source if they want the latest version for now. We can revisit whether we want to introduce some form of a canary release if requested by the community.

WDYT?
